"""
PrintBar Backend — System-Wide Constants

All constant values used across the PrintBar backend are defined here.
No magic numbers or strings anywhere else in the codebase.
"""

# ─── API ───────────────────────────────────────────────────────────────────────
API_VERSION = "v1"
API_PREFIX = f"/api/{API_VERSION}"

# ─── WebSocket Message Types ───────────────────────────────────────────────────
# Client → Server
WS_MSG_AUTH = "AUTH"
WS_MSG_PING = "PING"
WS_MSG_PONG = "PONG"
WS_MSG_HEARTBEAT = "HEARTBEAT"
WS_MSG_ACK = "ACK"
WS_MSG_ERROR = "ERROR"

# Server → Client
WS_MSG_NEW_JOB = "NEW_JOB"
WS_MSG_CANCEL_JOB = "CANCEL_JOB"
WS_MSG_JOB_STATUS = "JOB_STATUS"
WS_MSG_CONFIG_UPDATE = "CONFIG_UPDATE"
WS_MSG_MAINTENANCE = "MAINTENANCE"
WS_MSG_SHUTDOWN = "SHUTDOWN"

# ─── Print Job Status Values ───────────────────────────────────────────────────
JOB_STATUS_UPLOADED = "UPLOADED"
JOB_STATUS_VALIDATED = "VALIDATED"
JOB_STATUS_PAYMENT_PENDING = "PAYMENT_PENDING"
JOB_STATUS_PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
JOB_STATUS_QUEUED = "QUEUED"
JOB_STATUS_ASSIGNED = "ASSIGNED"
JOB_STATUS_DOWNLOADING = "DOWNLOADING"
JOB_STATUS_READY_TO_PRINT = "READY_TO_PRINT"
JOB_STATUS_PRINTING = "PRINTING"
JOB_STATUS_COMPLETED = "COMPLETED"
JOB_STATUS_FAILED = "FAILED"
JOB_STATUS_CANCELLED = "CANCELLED"
JOB_STATUS_PAYMENT_FAILED = "PAYMENT_FAILED"
JOB_STATUS_DOWNLOAD_FAILED = "DOWNLOAD_FAILED"

# Valid forward-only state transitions for print jobs
VALID_JOB_TRANSITIONS: dict[str, list[str]] = {
    JOB_STATUS_UPLOADED: [JOB_STATUS_VALIDATED, JOB_STATUS_FAILED],
    JOB_STATUS_VALIDATED: [JOB_STATUS_PAYMENT_PENDING, JOB_STATUS_FAILED],
    JOB_STATUS_PAYMENT_PENDING: [JOB_STATUS_PAYMENT_SUCCESS, JOB_STATUS_PAYMENT_FAILED, JOB_STATUS_CANCELLED],
    JOB_STATUS_PAYMENT_SUCCESS: [JOB_STATUS_QUEUED],
    JOB_STATUS_QUEUED: [JOB_STATUS_ASSIGNED, JOB_STATUS_CANCELLED],
    JOB_STATUS_ASSIGNED: [JOB_STATUS_DOWNLOADING],
    JOB_STATUS_DOWNLOADING: [JOB_STATUS_READY_TO_PRINT, JOB_STATUS_DOWNLOAD_FAILED],
    JOB_STATUS_READY_TO_PRINT: [JOB_STATUS_PRINTING],
    JOB_STATUS_PRINTING: [JOB_STATUS_COMPLETED, JOB_STATUS_FAILED],
    JOB_STATUS_COMPLETED: [],
    JOB_STATUS_FAILED: [],
    JOB_STATUS_CANCELLED: [],
    JOB_STATUS_PAYMENT_FAILED: [],
    JOB_STATUS_DOWNLOAD_FAILED: [JOB_STATUS_DOWNLOADING, JOB_STATUS_FAILED],
}

# ─── Payment Status Values ─────────────────────────────────────────────────────
PAYMENT_STATUS_CREATED = "CREATED"
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_PROCESSING = "PROCESSING"
PAYMENT_STATUS_SUCCESS = "SUCCESS"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_EXPIRED = "EXPIRED"
PAYMENT_STATUS_REFUNDED = "REFUNDED"

VALID_PAYMENT_TRANSITIONS: dict[str, list[str]] = {
    PAYMENT_STATUS_CREATED: [PAYMENT_STATUS_PENDING],
    PAYMENT_STATUS_PENDING: [PAYMENT_STATUS_PROCESSING, PAYMENT_STATUS_FAILED, PAYMENT_STATUS_EXPIRED],
    PAYMENT_STATUS_PROCESSING: [PAYMENT_STATUS_SUCCESS, PAYMENT_STATUS_FAILED],
    PAYMENT_STATUS_SUCCESS: [PAYMENT_STATUS_REFUNDED],
    PAYMENT_STATUS_FAILED: [],
    PAYMENT_STATUS_EXPIRED: [],
    PAYMENT_STATUS_REFUNDED: [],
}

# ─── Kiosk Status Values ───────────────────────────────────────────────────────
KIOSK_STATUS_ONLINE = "ONLINE"
KIOSK_STATUS_OFFLINE = "OFFLINE"
KIOSK_STATUS_PRINTING = "PRINTING"
KIOSK_STATUS_MAINTENANCE = "MAINTENANCE"
KIOSK_STATUS_ERROR = "ERROR"

# ─── Printer Status Values ─────────────────────────────────────────────────────
PRINTER_STATUS_READY = "READY"
PRINTER_STATUS_PRINTING = "PRINTING"
PRINTER_STATUS_OFFLINE = "OFFLINE"
PRINTER_STATUS_PAPER_JAM = "PAPER_JAM"
PRINTER_STATUS_OUT_OF_PAPER = "OUT_OF_PAPER"
PRINTER_STATUS_OUT_OF_TONER = "OUT_OF_TONER"

# ─── User Roles ────────────────────────────────────────────────────────────────
ROLE_GUEST = "GUEST"
ROLE_ADMIN = "ADMIN"
ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_KIOSK = "KIOSK"

# ─── Payment Gateway ───────────────────────────────────────────────────────────
PAYMENT_GATEWAY_EASEBUZZ = "EASEBUZZ"
PAYMENT_GATEWAY_RAZORPAY = "RAZORPAY"

# ─── Currency ──────────────────────────────────────────────────────────────────
DEFAULT_CURRENCY = "INR"

# ─── File & Storage ────────────────────────────────────────────────────────────
PDF_EXTENSION = ".pdf"
PDF_MIME_TYPE = "application/pdf"
PDF_MAGIC_BYTES = b"%PDF"

# ─── Color Modes ───────────────────────────────────────────────────────────────
COLOR_MODE_BW = "BW"
COLOR_MODE_COLOR = "COLOR"

# ─── Paper Sizes ───────────────────────────────────────────────────────────────
PAPER_SIZE_A4 = "A4"
PAPER_SIZE_A3 = "A3"
PAPER_SIZE_LETTER = "LETTER"
PAPER_SIZE_LEGAL = "LEGAL"

# ─── Error Code Prefixes ───────────────────────────────────────────────────────
ERROR_UPLOAD = "UPLOAD"
ERROR_PAYMENT = "PAY"
ERROR_PRINTER = "PRINTER"
ERROR_KIOSK = "KIOSK"
ERROR_JOB = "JOB"
ERROR_AUTH = "AUTH"
ERROR_SESSION = "SESSION"
ERROR_STORAGE = "STORAGE"
ERROR_SYSTEM = "SYS"

# ─── Specific Error Codes ──────────────────────────────────────────────────────
ERR_UPLOAD_UNSUPPORTED_TYPE = "UPLOAD_001"
ERR_UPLOAD_FILE_TOO_LARGE = "UPLOAD_002"
ERR_UPLOAD_INVALID_PDF = "UPLOAD_003"
ERR_UPLOAD_PASSWORD_PROTECTED = "UPLOAD_004"
ERR_UPLOAD_EMBEDDED_JS = "UPLOAD_005"
ERR_UPLOAD_EMBEDDED_FILES = "UPLOAD_006"
ERR_UPLOAD_ZERO_PAGES = "UPLOAD_007"
ERR_UPLOAD_CORRUPTED = "UPLOAD_008"
ERR_UPLOAD_TOO_MANY_PAGES = "UPLOAD_009"

ERR_PAY_INVALID_SIGNATURE = "PAY_001"
ERR_PAY_TIMEOUT = "PAY_002"
ERR_PAY_AMOUNT_MISMATCH = "PAY_003"
ERR_PAY_DUPLICATE = "PAY_004"
ERR_PAY_GATEWAY_ERROR = "PAY_005"
ERR_PAY_UNKNOWN_ORDER = "PAY_006"
ERR_PAY_CURRENCY_MISMATCH = "PAY_007"

ERR_AUTH_INVALID_TOKEN = "AUTH_001"
ERR_AUTH_EXPIRED_TOKEN = "AUTH_002"
ERR_AUTH_INVALID_CREDENTIALS = "AUTH_003"
ERR_AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_004"

ERR_JOB_NOT_FOUND = "JOB_001"
ERR_JOB_INVALID_TRANSITION = "JOB_002"
ERR_JOB_NO_KIOSK_AVAILABLE = "JOB_003"

ERR_KIOSK_NOT_REGISTERED = "KIOSK_001"
ERR_KIOSK_OFFLINE = "KIOSK_002"
ERR_KIOSK_INVALID_API_KEY = "KIOSK_003"

# ─── Audit Actions ────────────────────────────────────────────────────────────
AUDIT_UPLOAD_CREATED = "UPLOAD_CREATED"
AUDIT_UPLOAD_VALIDATED = "UPLOAD_VALIDATED"
AUDIT_UPLOAD_DELETED = "UPLOAD_DELETED"
AUDIT_PAYMENT_CREATED = "PAYMENT_CREATED"
AUDIT_PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
AUDIT_PAYMENT_FAILED = "PAYMENT_FAILED"
AUDIT_JOB_CREATED = "JOB_CREATED"
AUDIT_JOB_STATUS_CHANGED = "JOB_STATUS_CHANGED"
AUDIT_JOB_COMPLETED = "JOB_COMPLETED"
AUDIT_JOB_FAILED = "JOB_FAILED"
AUDIT_JOB_CANCELLED = "JOB_CANCELLED"
AUDIT_KIOSK_REGISTERED = "KIOSK_REGISTERED"
AUDIT_KIOSK_AUTHENTICATED = "KIOSK_AUTHENTICATED"
AUDIT_KIOSK_OFFLINE = "KIOSK_OFFLINE"
AUDIT_ADMIN_LOGIN = "ADMIN_LOGIN"
AUDIT_ADMIN_LOGOUT = "ADMIN_LOGOUT"
AUDIT_PRICING_UPDATED = "PRICING_UPDATED"
AUDIT_API_KEY_ROTATED = "API_KEY_ROTATED"
AUDIT_FILE_CLEANUP = "FILE_CLEANUP"
